### ISSUE TITLE
Missing references in TaskWebApp to Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory

### ISSUE THREAD

**Issue by danroth27** [AzureADQuickStarts/B2C-WebAPI-DotNet#12]
Missing references Microsoft.Experimental.IdentityModel.Clients.ActiveDirectory.* libraries

**Comment by andrewchilcott** [comment]
This example breaks when using latest versions of assemblies and setting project to target Net452 instead of Net45

OpenIdConnectAuthenticationOptions defines TokenValidationParameters in System.IdentityModel.Tokens.  However TokenValidationParameters  is now defined in Microsoft.IdentityModel.Tokens. 

I get an error at Line 79 in TaskWebApp - Reference to type 'TokenValidationParameters' claims it is defined in 'System.IdentityModel.Tokens.Jwt' , but it could not be found

Can anyone suggest a work around

**Comment by gsacavdm** [comment]
@andrewchilcott , this sample has been deprecated. Check out our [newer sample](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi).

How did you come across this sample?
We want to make sure all links to point to the new sample.

**Comment by danroth27** [comment]
I ran across this samples org in the B2C docs: Ex. https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-web-dotnet.

**Comment by gsacavdm** [comment]
Thanks @danroth27, we'll update that doc accordingly.
